### ISSUE TITLE
Can't seem to get this to work locally

### ISSUE THREAD

**Issue by TheWing** [rastapasta/mapscii#16]
I've followed the 'instructions', and looked around for what I can see myself, but can't find a proper reason for this happening when trying to run mapscii.
```
$ mapscii
Unhandled rejection TypeError: Object http://mapscii.me/ has no method 'startsWith'
    at TileSource.module.exports.TileSource.init (/usr/local/lib/node_modules/mapscii/src/TileSource.coffee:38:16)
    at Mapscii.module.exports.Mapscii._initTileSource (/usr/local/lib/node_modules/mapscii/src/Mapscii.coffee:61:17)
    at /usr/local/lib/node_modules/mapscii/src/Mapscii.coffee:51:8
    at tryCatcher (/usr/local/lib/node_modules/mapscii/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/mapscii/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/mapscii/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/usr/local/lib/node_modules/mapscii/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/usr/local/lib/node_modules/mapscii/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/usr/local/lib/node_modules/mapscii/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/usr/local/lib/node_modules/mapscii/node_modules/bluebird/js/release/async.js:17:14)
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by rastapasta** [comment]
could you check with
```sh
$ node -v
```
if your version is >= 4 (best >= 7)

**Comment by TheWing** [comment]
I do have node v7.10.0, so that shouldn't be the problem.. for one there's some deprecations with the npm install:
```
npm WARN engine mapscii@0.1.4: wanted: {"node":">=4.5.0"} (current:  {"node":"0.10.29","npm":"1.4.21"})
npm WARN deprecated vector-tile@1.3.0: This module has moved: please install @mapbox/vector-tile instead
npm WARN deprecated point-geometry@0.0.0: This module has moved: please install @mapbox/point-geometry instead
/usr/local/bin/mapscii -> /usr/local/lib/node_modules/mapscii/bin/mapscii.sh
mapscii@0.1.4 /usr/local/lib/node_modules/mapscii
├── term-mouse@0.1.1
├── simplify-js@1.2.1
├── userhome@1.0.0
├── keypress@0.2.1
├── bresenham@0.0.4
├── x256@0.0.2
├── earcut@2.1.1
├── coffee-script@1.12.5
├── rbush@2.0.1 (quickselect@1.0.0)
├── vector-tile@1.3.0 (point-geometry@0.0.0)
├── bluebird@3.5.0
├── node-fetch@1.6.3 (is-stream@1.1.0, encoding@0.1.12)
└── pbf@3.0.5 (ieee754@1.1.8, resolve-protobuf-schema@2.0.0)
```

**Comment by TheWing** [comment]
hmm.. no idea why it says node 0.10.29 there, though, this is what I get with node -v
```
$ node -v
v7.10.0

```

**Comment by rastapasta** [comment]
the `npm` you used to install `mapscii` most likely belongs to the parallel install of 0.10.29 - check with

```sh
$ which node
$ which npm
```

if both map to the same installation - and maybe switch to a environment like [n](https://github.com/tj/n) or [nvm](https://github.com/creationix/nvm) to make the version hassle an easy ride 🏇

**Comment by TheWing** [comment]
alright, version hassles done and up to date, but the original error still remains; http://mapscii.me/ has no method 'startsWith'

**Comment by derhuerst** [comment]
@TheWing Did you install with a fresh `node_modules` dir?

**Comment by TheWing** [comment]
sure

**Comment by derhuerst** [comment]
i assume after untangling the version hassle? 😉

**Comment by rastapasta** [comment]
Closing, as its not an issue with the code. Cheers!
