### ISSUE TITLE
Pressing Escape crashes local Mapscii

### ISSUE THREAD

**Issue by jaller94** [rastapasta/mapscii#34]
### Reproduce:
1. Start Mapscii with `npm run start`
2. Press Escape on the keyboard

### Affected
Tested on
- Ubuntu 17.10 with gnome-terminal
- npm@5.4.2
- node@v8.1.3

Only my local mapscii (version 1251e3f25713213ca5891c8f646e19f8b24ce9b2) is affected.

### Expected:
Mapscii ignores this or quits.

### Actual:
Mapscii crashes

```
  throw new ERR_OUT_OF_RANGE(type || 'offset',
  ^

RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 0. Received 1
    at boundsError (internal/buffer.js:58:9)
    at Buffer.readUInt8 (internal/buffer.js:148:5)
    at Mouse._onData (/home/jaller94/Git/github/mapscii/node_modules/term-mouse/index.js:81:24)
    at ReadStream.emit (events.js:198:15)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at ReadStream.Readable.push (_stream_readable.js:231:10)
    at TTY.onStreamRead (internal/stream_base_commons.js:154:17)
```

**Comment by dogabudak** [comment]
I opened a pull request in term-mouse library which causes this issue.

**Comment by rastapasta** [comment]
@dogabudak! Awesome intention and well executed, just released v.0.3.1 with updated dependencies after your PR got merged into a fresh term-mouse release. Thanks a lot for taking care & welcome on board the MapSCII train ;) 🚂
