### ISSUE TITLE
Unhandled rejection TypeError: require(...).setRawMode is not a function

### ISSUE THREAD

**Issue by ceemomx** [rastapasta/mapscii#39]
windows10
node v10.1.0
gitbash

use `npm install -g mapscii`
and it works fine
then i try `mapscii`
it throw an error
```javascript
Unhandled rejection TypeError: require(...).setRawMode is not a function
    at Mouse.start (C:\Users\c\AppData\Roaming\npm\node_modules\mapscii\node_modules\term-mouse\index.js:67:21)
    at Mapscii.module.exports.Mapscii._initMouse (C:\Users\c\AppData\Roaming\npm\node_modules\mapscii\src\Mapscii.coffee:73:12)
    at C:\Users\c\AppData\Roaming\npm\node_modules\mapscii\src\Mapscii.coffee:49:10
    at tryCatcher (C:\Users\c\AppData\Roaming\npm\node_modules\mapscii\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\c\AppData\Roaming\npm\node_modules\mapscii\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\c\AppData\Roaming\npm\node_modules\mapscii\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromiseCtx (C:\Users\c\AppData\Roaming\npm\node_modules\mapscii\node_modules\bluebird\js\release\promise.js:606:10)
    at Async._drainQueue (C:\Users\c\AppData\Roaming\npm\node_modules\mapscii\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (C:\Users\c\AppData\Roaming\npm\node_modules\mapscii\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\c\AppData\Roaming\npm\node_modules\mapscii\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)

```

**Comment by Sloansta** [comment]
When I run this in Windows using Gitbash I get this error, however if I run it in Powershell I get a completely different one. I cloned the repo on my Mac and all is fine. Seems like it might be a Windows specific issue.

Try running it in Powershell, see if you get a different error.
