### ISSUE TITLE
After a series of operations, there is a line shows"renderer is busy".

### ISSUE THREAD

**Issue by Vinniero** [rastapasta/mapscii#50]
throw new ERR_OUT_OF_RANGE(type || 'offset',
  ^

RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 0. Received 1
    at boundsError (internal/buffer.js:54:9)
    at Uint8Array.readUInt8 (internal/buffer.js:144:5)
    at Mouse._onData (/usr/local/lib/node_modules/mapscii/node_modules/term-mouse/index.js:81:24)
    at ReadStream.emit (events.js:187:15)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at ReadStream.Readable.push (_stream_readable.js:219:10)
    at TTY.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

**Comment by Vinniero** [comment]
****
