### ISSUE TITLE
local npm install: "Error: Unimplemented type: 4" - broken PBF cache

### ISSUE THREAD

**Issue by Piskvor** [rastapasta/mapscii#71]
**Steps to reproduce**

- Install mapscii by npm, or by snap (Kubuntu Linux 18.04.2 Bionic Beaver)
- Run `mapscii`
- Get error

**Current behavior**

- sudo npm install -g mapscii
```
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
/usr/bin/mapscii -> /usr/lib/node_modules/mapscii/bin/mapscii.sh
+ mapscii@0.1.7
added 27 packages from 20 contributors in 1.517s
```
- mapscii
```
Error: Unimplemented type: 4
    at Pbf.skip (/usr/lib/node_modules/mapscii/node_modules/pbf/index.js:200:20)
    at Pbf.readFields (/usr/lib/node_modules/mapscii/node_modules/pbf/index.js:41:45)
    at new VectorTile (/usr/lib/node_modules/mapscii/node_modules/@mapbox/vector-tile/lib/vectortile.js:8:23)
    at Tile._loadTile (/usr/lib/node_modules/mapscii/src/Tile.coffee:31:13)
    at /usr/lib/node_modules/mapscii/src/Tile.coffee:26:24
    at tryCatcher (/usr/lib/node_modules/mapscii/node_modules/bluebird/js/release/util.js:16:23)                                                                                             
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/mapscii/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/usr/lib/node_modules/mapscii/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromiseCtx (/usr/lib/node_modules/mapscii/node_modules/bluebird/js/release/promise.js:611:10)
    at _drainQueueStep (/usr/lib/node_modules/mapscii/node_modules/bluebird/js/release/async.js:142:12)
    at _drainQueue (/usr/lib/node_modules/mapscii/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/usr/lib/node_modules/mapscii/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/mapscii/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

Welcome to MapSCII! Use your cursors to navigate, a/z to zoom, q to quit.
```

**Expected behavior**

- map displayed.

**Steps to fix**
- `rm -rf ~/.mapscii/cache`
- app starts normally

**Comment by Piskvor** [comment]
According to https://wiki.openstreetmap.org/wiki/PBF_Format , Type 4 is `optional Info info = 4; // May be omitted in omitmeta` - perhaps the downloaded mapfile was corrupt?

Perhaps this could be handled in-app, or at least given a more descriptive error message - meanwhile, the error and fix is discoverable here.
