### ISSUE TITLE
Unimplemented type: 4

### ISSUE THREAD

**Issue by harriott** [rastapasta/mapscii#87]
**Steps to reproduce**
`linux 5.7.4.arch1-1`, in either `urxvt` or `xterm`:
```bash
$ npx mapscii
Welcome to MapSCII! Use your cursors to navigate, a/z to zoom, q to quit.Error: Unimplemented type: 4
    at Pbf.skip (/usr/lib/node_modules/mapscii/node_modules/pbf/index.js:211:20)
    at Pbf.readFields (/usr/lib/node_modules/mapscii/node_modules/pbf/index.js:46:45)
    at new VectorTile (/usr/lib/node_modules/mapscii/node_modules/@mapbox/vector-tile/lib/vectortile.js:8:23)
    at Tile._loadTile (/usr/lib/node_modules/mapscii/src/Tile.js:33:17)
    at /usr/lib/node_modules/mapscii/src/Tile.js:24:19
renderer is busy
```
and nothing more appears - no map. Exactly the same when I run `mapscii` installed from `AUR`.

**Comment by Quillbert** [comment]
I have been getting this same error on a Raspberry Pi Zero It only occurs when 2<=zoom<3.

**Comment by NeilsC** [comment]
Same issue on Ubuntu 20.04 with mapscii v0.3.1 installed via snap.

Welcome to MapSCII! Use your cursors to navigate, a/z to zoom, q to quit.Error: Unimplemented type: 4
    at Pbf.skip (/snap/mapscii/14/lib/node_modules/mapscii/node_modules/pbf/index.js:211:20)
    at Pbf.readFields (/snap/mapscii/14/lib/node_modules/mapscii/node_modules/pbf/index.js:46:45)
    at new VectorTile (/snap/mapscii/14/lib/node_modules/mapscii/node_modules/@mapbox/vector-tile/lib/vectortile.js:8:23)
    at Tile._loadTile (/snap/mapscii/14/lib/node_modules/mapscii/src/Tile.js:33:17)
    at /snap/mapscii/14/lib/node_modules/mapscii/src/Tile.js:24:19

**Comment by dreirund** [comment]
I have this too; what is the state of fixing this?
